"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@asgardeo/auth-react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider
        config={{
          signInRedirectURL: "http://localhost:3000/jitsi",
          signOutRedirectURL: "http://localhost:3000",
          clientID: "1UfZ0yc9Htjt5BUITDvznQp0pEga",
          baseUrl: "https://api.asgardeo.io/t/sruvi",
          scope: ["openid", "profile"],
        }}
      >
        <body className={inter.className}>{children}</body>
      </AuthProvider>
    </html>
  );
}
